services:
  - type: web
    name: FantasyCyclingLeagueTools
    runtime: docker
    repo: https://github.com/lukegjpotter/FantasyCyclingLeagueTools
    dockerContext: .
    dockerfilePath: Dockerfile
    region: frankfurt
    plan: free
    healthCheckPath: /health
    numInstances: 1
    autoDeploy: false
    envVars:
      - key: ROADCC_LEAGUE_NAME
        sync: false
      - key: ROADCC_USERNAME
        sync: false
      - key: ROADCC_PASSWORD
        sync: false
      - key: IS_FANTASY_CYCLING_TOOLS_ON_DOCKER
        value: 'true'
version: "1"