@ECHO OFF

ECHO [info] Setting ROADCC_USERNAME
@SET ROADCC_USERNAME=yourusername
ECHO [info] Set ROADCC_USERNAME to %ROADCC_USERNAME%

ECHO [info] Setting ROADCC_PASSWORD
@SET ROADCC_PASSWORD=yourpassword
ECHO [info] Set ROADCC_PASSWORD to %ROADCC_PASSWORD%

ECHO [info] Setting ROADCC_LEAGUE_NAME
@SET ROADCC_LEAGUE_NAME=your league name
ECHO [info] Set ROADCC_LEAGUE_NAME to %ROADCC_LEAGUE_NAME%

ECHO [info] Setting IS_FANTASY_CYCLING_TOOLS_ON_DOCKER
@SET IS_FANTASY_CYCLING_TOOLS_ON_DOCKER=false
ECHO [info] Set IS_FANTASY_CYCLING_TOOLS_ON_DOCKER to %IS_FANTASY_CYCLING_TOOLS_ON_DOCKER%