@ECHO OFF

ECHO [info] Setting ROADCC_USERNAME
@SET ROADCC_USERNAME=yourusername
ECHO [info] Set ROADCC_USERNAME to %ROADCC_USERNAME%

ECHO [info] Setting ROADCC_PASSWORD
@SET ROADCC_PASSWORD=yourpassword
ECHO [info] Set ROADCC_PASSWORD to %ROADCC_PASSWORD%